### ISSUE TITLE
GLUON_ATH10K_MESH was renamed to GLUON_WLAN_MESH

### ISSUE THREAD

**Issue by ghost** [ffdo/site-ffdo-l2tp#6]
In your `site.mk` files `GLUON_ATH10K_MESH` is still in use. But it was renamed to `GLUON_WLAN_MESH` in Gluon v2018.1 https://gluon.readthedocs.io/en/v2018.1.x/releases/v2018.1.html#site-mk

At the moment `GLUON_ATH10K_MESH` is ignored and `GLUON_WLAN_MESH = 11s` is used.
https://gluon.readthedocs.io/en/v2018.1.x/user/site.html#build-configuration

**Comment by cajuskamer** [comment]
thx for reporting this issue.
